Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Data atual  : 27/12/2020
Var
 valor1, valor2 :inteiro
Inicio
 escreval ("digite um valor")
 leia(valor1)
 
 escreval("digite outro valor")
 leia(valor2)
 
 //adição
 escreval("adição: ", (valor1 + valor2))
 
 //subtração
 escreval("subtração: ", (valor1 - valor2))
 
 //multiplação
 escreval("multiplação: ", (valor1 * valor2))
 
 //divisão
 escreval("divisão: ", (valor1/valor2))
Fimalgoritmo