Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Data atual  : 27/12/2020
Var
 variavel1 :inteiro
 variavel2 :real
 variavel3 :caracter
 variavel4 :logico
Inicio

 variavel1 := 5
 variavel2 := 5,5
 variavel3 := "cinco"
 variavel4 := verdadeiro
 
 variavel1 := 0
 
 escreval(variavel1)
 escreval(variavel2)
 escreval(variavel3)
 escreval(variavel4)
 
 leia(variavel1)
 
 escreva(variavel1)
  
Fimalgoritmo